---
- hosts: localhost
  vars:
    state_bucket: "{{ state_bucket }}"
  tasks:
    - name: get_all_templates_file
      ansible.builtin.script:
        executable: python3
        cmd: get_all_templates_file.py
      register: templates

    - name: Render templates
      template:
        src: "{{ item }}"
        dest: "{{ item | replace('.j2', '') }}"
      vars:
        bucket: "{{ state_bucket }}"
      loop: "{{ templates.stdout }}"

    - name: Create resources
      shell: 
        cmd: "terraform init && terraform apply -var-file deploy.tfvars -auto-approve"
        chdir: "{{ item }}"
      loop:
        - "infra/vpc"
        - "infra/gke"
        - "infra/db"
        - "infra/registry"
